# Getting started with Julia
(and if you get the subliminal message about abstractions, we'll be thrilled!)

Julia is a dynamic language.  You don't need type declarations, and can change variable types dynamically and interactively.

For working with simple numbers, arrays, and strings, its syntax is *superficially* similar to Matlab, Python, and other popular languages.

In order to execute the `In` cells, select the cell and press `Shift-Enter`, or press the `Play` button above. To run the entire notebook, navigate to the `Cell` menu and then `Run All`.

# We tell beginners, you don't need types!

In [1]:
typeof(1.0)

Float64

In [2]:
typeof(1)

Int64

In [3]:
S = "Hello Julia Clsas"
typeof(S)

String

In [4]:
#  Exercise fix my spelling in the cell above
S

"Hello Julia Clsas"

# Now forget all that (for now): Julia is not so different from your favorite dynamic language

In [5]:
1 + 1  # shift + enter to run

2

In [6]:
A = rand(5, 5)

5×5 Array{Float64,2}:
 0.242515  0.57047    0.676065   0.783181  0.336732
 0.749483  0.355323   0.306982   0.168056  0.112884
 0.515221  0.0107378  0.82184    0.147794  0.303414
 0.622014  0.791245   0.290158   0.379897  0.14828 
 0.39159   0.346487   0.0763914  0.476341  0.246738

In [7]:
A = SymTridiagonal(rand(6), rand(5))

6×6 SymTridiagonal{Float64}:
 0.402972     0.000228727   ⋅         ⋅         ⋅         ⋅      
 0.000228727  0.942867     0.14092    ⋅         ⋅         ⋅      
  ⋅           0.14092      0.426505  0.376577   ⋅         ⋅      
  ⋅            ⋅           0.376577  0.634101  0.505507   ⋅      
  ⋅            ⋅            ⋅        0.505507  0.699003  0.292883
  ⋅            ⋅            ⋅         ⋅        0.292883  0.689933

In [8]:
b = rand(6)
A \ b

6-element Array{Float64,1}:
  1.57178 
  0.420302
  0.623034
  1.22367 
 -0.990591
  1.23609 

In [9]:
A = fill(3.15, 5, 5) # Fill a 5x5 array with 3.15's

5×5 Array{Float64,2}:
 3.15  3.15  3.15  3.15  3.15
 3.15  3.15  3.15  3.15  3.15
 3.15  3.15  3.15  3.15  3.15
 3.15  3.15  3.15  3.15  3.15
 3.15  3.15  3.15  3.15  3.15

# Let's create some addition tables

First let's use a nested for loop to fill in a matrix that's initially zero:

In [10]:
A = zeros(5, 5)

for i in 1:5
    for j in 1:5
        A[i, j] = i+j  # Square brackets for indices.  Also: indices start at 1, not 0.
    end
end

A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

We can abbreviate this using a double `for` loop:

In [11]:
for i in 1:5, j in 1:5
   A[i, j] = i+j  # Square brackets for indices.  Also: indices start at 1, not 0.
end

A

5×5 Array{Float64,2}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

The Julia way would be to use a so-called **array comprehension**:

In [12]:
[i+j for i in 1:5, j in 1:5]

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [13]:
# Equivalently,
[i+j for i = 1:5, j = 1:5]

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

**Explore**: What does the following do? 

In [14]:
[i for i in (1:7).^2]

7-element Array{Int64,1}:
  1
  4
  9
 16
 25
 36
 49

In [1]:
# What happens when  we remove the dot syntax?
[i for i in (1:7)^2]

LoadError: DimensionMismatch("Cannot multiply two vectors")

In [16]:
[i^2 for i in 1:7]

7-element Array{Int64,1}:
  1
  4
  9
 16
 25
 36
 49

**Explore**: What does the following do? 

In [17]:
sort(unique(x^2 + y^2 for x in 1:5, y in 1:5))  # The inner parentheses define a **generator**

15-element Array{Int64,1}:
  2
  5
  8
 10
 13
 17
 18
 20
 25
 26
 29
 32
 34
 41
 50

Suppose we want to see $n \times n$ multiplication tables for $n=1,2,3,4,5$:

In [18]:
for n in 1:5
    display([i*j for i=1:n, j=1:n])
end

1×1 Array{Int64,2}:
 1

2×2 Array{Int64,2}:
 1  2
 2  4

3×3 Array{Int64,2}:
 1  2  3
 2  4  6
 3  6  9

4×4 Array{Int64,2}:
 1  2   3   4
 2  4   6   8
 3  6   9  12
 4  8  12  16

5×5 Array{Int64,2}:
 1   2   3   4   5
 2   4   6   8  10
 3   6   9  12  15
 4   8  12  16  20
 5  10  15  20  25

# `Interact.jl` is a Julia *package* for interacting with data

It's way more fun to **interact** with our data.
We install the `Interact.jl` package as follows; this needs to be executed only once for any given Julia installation:

Now we load the package with the following `using` command, in each Julia session:

In [20]:
using Interact

INFO: Updating cache of Interact...
INFO: Updating cache of Reactive...
INFO: Installing Interact v0.6.2
INFO: Installing Reactive v0.6.0
INFO: Building Interact
  likely near /Users/ranjan/.julia/v0.6/Interact/deps/build.jl:39
  likely near /Users/ranjan/.julia/v0.6/Interact/deps/build.jl:39
INFO: Enabling widgetsnbextension
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
INFO: ipywidgets version found: 6.0.0
INFO: A compatible version of ipywidgets was found. All good.
INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of Interact
INFO: Use `Pkg.update()` to get the latest versions of your packages
INFO: Precompiling module Interact.


The package contains a `@manipulate` macro, that is wrapped around a `for` loop:

In [ ]:
@manipulate for n in 1:1000
    n
end

In [ ]:
@manipulate for n in 1:20
    [i*j for i in 1:n, j in 1:n]
end

We use a double `for` loop to get a double slider!

In [ ]:
@manipulate for n in 3:10, i in 1:9
   A = fill(0, n, n)
   A[1:3, 1:3] = i    # fill a sub-block
A
end

# Functions

Julia is built around functions: all "commands" or "operations" in Julia are functions:

In [ ]:
# verbose form:
function f(x)
    x^2
end

# one-line form:
f2(x) = x^2

# anonymous form:
f3 = x -> x^2;

In [ ]:
f(10)

Functions just work, as long as they make sense:

In [ ]:
# The square of a matrix is unambiguously defined
f(rand(3, 3))

In [ ]:
# What the 'square of a vector' means is ambiguous
f(rand(3))

In [ ]:
# In the definition below, `a` and `power` are optional arguments to `f`, supplied with default values.
function f(x, a=1, power=2)
    a*x^power
end

In [ ]:
# `a` defaults to 1 and `power` to 2
f(7)

In [ ]:
# The first optional argument passed is assigned to the local variable `a`
# `power` defaults to 2
f(10, 3)

In [ ]:
f(10, 3, 3)

Let's define a function to insert a block in a matrix:

In [ ]:
function insert_block(A, i, j, what=7)
    B = A[:,:]        # B is a copy of A       
    B[i:i+2, j:j+2] = fill(what, 3, 3)
    
    return B          # the `return` keyword is optional
end

In [ ]:
A = fill(0, 9, 9)
insert_block(A, 3, 5)  # this returns the new matrix

In [ ]:
A = fill(0, 9, 9)
insert_block(A, 3, 5, 2)  # Use 2 instead of 7

We can move the block around:

In [ ]:
A = fill(0, 10, 10)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j)
end

# Strings

Julia can manipulate strings easily:

In [ ]:
S = "Hello"

In [ ]:
replace(S, "H", "J")

In [ ]:
a = 3

In [ ]:
string(S, " ", S, " ", "Julia; a = ", a)  # build a string by concatenating things

More about strings: <a href="http://docs.julialang.org/en/stable/manual/strings/"> Julia Doc on Strings </a>

Functions in Julia try to be **generic**, i.e. to work with as many kinds of object as possible:

In [ ]:
A = fill("Julia", 5, 5)

Julia allows us to display objects in different ways. For example, the following code displays a matrix of strings
in the notebook using an HTML representation:

In [ ]:
function Base.show{T<:String}(io::IO, ::MIME"text/html", M::Matrix{T}) 
    max_length = maximum(length.(M))
    dv="<div style='display:flex;flex-direction:row'>"
    print(io, dv*join([join("<div style='width:40px; text-align:center'>".*M[i,:].*"</div>", " ") for i in 1:size(M, 1)]
            , "</div>$dv")*"</div>")
end

In [ ]:
A

In [ ]:
# Remember this ????
A = fill(0, 10, 10)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i,j)
end

Let's use the **same code**, but now with strings:

In [ ]:
A = fill("Julia", 10, 10)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i,j, "[FUN]")
end

In [ ]:
@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j, "π")
end

In [ ]:
@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j, "♡")
end

In [ ]:
airplane = "✈"
alien = "👽"
rand([airplane, alien], 5, 5)

In [ ]:
A = fill(airplane, 9, 9)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j, alien)
end

# Colors

The `Colors` package provides objects representing colours:

In [ ]:
using Colors

In [ ]:
distinguishable_colors(12)

In [ ]:
@manipulate for n in 1:80
    distinguishable_colors(n)
end

In [ ]:
colors = distinguishable_colors(100)


In [ ]:
# Remember this ????
A = fill(0, 10, 10)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j)
end

What happens if we use colors instead?

In [ ]:
A = fill(colors[1], 10, 10)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j, colors[4])
end

In [ ]:
# Exercise: Create Tetris Pieces, have them fall from the top